# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d7cffff1c22c8d9c0a5886b48c2ac929c691ce66fc8e28ae95c499f27b52c0b95f8311b3bc8c522c5a27574db1e7fac65329c5405902fcdc5f805ea1596979b

test:
  secret_key_base: 6f4fa67e46989a386a35266fa6144fb0949418a58e6a5eedd4180daafd0059c6f2565e8205494f5c2ca9d1e4f8b1ed08163226a3966387a477fc8ea4d1391954

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
